### ISSUE TITLE
where is the data in the project?

### ISSUE THREAD

**Issue by demainchen** [QData/DeepVHPPI#1]
(demainchen) demainchen@chenwenqideMacBook-Air DeepVHPPI-main % python main.py --data_root ./data/data/ -tr yang_ppi/train.json -va yang_ppi/test.json -te HVPPI/test.json -v vocab.data -s 1024 -hs 512 -l 12 -o results --lr 0.00001 --dropout 0.1 --epochs 200 --attn_heads 8 --activation 'gelu' --task biogrid --emb_type 'conv' --overwrite --batch_size 4 --grad_ac_steps 4
Loading Vocab ./data/data/vocab.data
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    vocab = WordVocab.load_vocab(args.vocab_path)
  File "/Users/demainchen/Downloads/DeepVHPPI-main/data/vocab.py", line 169, in load_vocab
    with open(vocab_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/data/vocab.data'

**Comment by jacklanchantin** [comment]
Added in the readme:
```
wget https://www.cs.virginia.edu/yanjun/jack/ppi/deepvhppi.tar.gz
tar -xvf deepvhppi.tar.gz
```

**Comment by Davegb** [comment]
@jacklanchantin The link is dead. Could you reupload it, please?

**Comment by jacklanchantin** [comment]
It's fixed in the readme:

wget https://www.cs.virginia.edu/yanjun/jack/ppi/deepvhppi.tar.gz
tar -xvf deepvhppi.tar.gz
