### ISSUE TITLE
It looks like some important file missing

### ISSUE THREAD

**Issue by demainchen** [QData/DeepVHPPI#2]
When I try to run the code, I met the error.
(demainchen) demainchen@chenwenqideMacBook-Air DeepVHPPI-main % CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --data_root ./data/ -tr yang/train.json -va yang/test.json -te  HVPPI/test.json -v vocab.data -s 1024 -hs 512 -l 12  -o results  --lr 0.00001 --dropout 0.1 --epochs 200 --attn_heads 8 --activation 'gelu' --task biogrid  --emb_type 'conv' --overwrite  --batch_size 4 --grad_ac_steps 4

Loading Vocab ./data/vocab.data
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    vocab = WordVocab.load_vocab(args.vocab_path)
  File "/Users/demainchen/Downloads/DeepVHPPI-main/data/vocab.py", line 169, in load_vocab
    with open(vocab_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/vocab.data'
If you don't mind, Could you please submit the vocab.data?

**Comment by wesleywt** [comment]
Hi. I am also trying to run this code, I am wondering if the vocab.data file will be uploaded or what the method is to generate this file. Also, will any of the models trained be made available?

**Comment by wesleywt** [comment]
Hi. I created vocab.data using vocab.py and pfam sequences. Not sure if it is correct. But it works until next error.

**Comment by jacklanchantin** [comment]
Hi, what @wesleywt should work, but I have provided my vocab file here: https://www.cs.virginia.edu/yanjun/jack/ppi/data/vocab.data (1.5K)

**Comment by Davegb** [comment]
@jacklanchantin The link is dead for this file, and it's not in the big data file pointed in the README. Could you reupload it, please?

**Comment by jacklanchantin** [comment]
Sorry, updated here: https://www.cs.virginia.edu/yanjun/jack/ppi/data/vocab.data (1.5K)
